### ISSUE TITLE
Track List & Roadmap

### ISSUE THREAD

**Issue by yozora3** [OpenTTD-JPplus/JPplusTracks#1]
## Narrow Gauge
_Narrow NE_
- [x] Narrow 80Km/h (Non-Electric)
- [x] Narrow Urban 130Km/h (Non-Electric)
- [x] Narrow 130Km/h (Non-Electric)
- [x] Narrow 160Km/h (Non-Electric)

_Narrow DC_
- [x] Narrow Urban 130Km/h (DC Electric)
- [x] Narrow 130Km/h (DC Electric)
- [x] Narrow 160Km/h (DC Electric)

_Narrow AC_
- [x] Narrow Urban 130Km/h (AC Electric)
- [x] Narrow 130Km/h (AC Electric)
- [x] Narrow 160Km/h (AC Electric)

_Narrow AC/DC_
- [x] Narrow 130Km/h (ACDC Electric)
- [x] Narrow 130Km/h (ACDC Electric)

## Scotch Gauge
- [x] Scotch Urban 130Km/h (DC Electric)
- [x] Scotch 130Km/h (DC Electric)
- [x] Scotch 160Km/h (DC Electric)

## Standard Gauge
_Hide NE for Japan Preset_

_Standard NE_
- [x] Standard 80Km/h (Non-Electric)
- [x] Standard Urban 130Km/h (Non-Electric)
- [x] Standard 130Km/h (Non-Electric)
- [x] Standard 160Km/h (Non-Electric)

_Standard DC_
- [x] Standard Urban 130Km/h (DC Electric)
- [x] Standard 130Km/h (DC Electric)
- [x] Standard 160Km/h (DC Electric)

_Standard AC_
- [x] Standard Urban 130Km/h (AC Electric)
- [x] Standard 130Km/h (AC Electric)
- [x] Standard 160Km/h (AC Electric)

_Standard AC/DC_
- [x] Standard 130Km/h (ACDC Electric)
- [x] Standard 130Km/h (ACDC Electric)

_Standard Third Rail_
- [x] Standard Urban 130Km/h (Third-Rail)
- [x] Standard 130Km/h (Third-Rail)

_Standard LinMo_
- [x] Standard Urban 130Km/h (LinMo)
- [x] Standard 130Km/h (LinMo)

_Shinkansen_
- [x] Standard High-Speed 260Km/h (Electric)
- [x] Standard Modern High-Speed (Electric)

## Dual Gauge
- [x] Dual-Gauge 130Km/h (Non-Electric)
- [x] Dual-Gauge 130Km/h (AC/DC)
- [x] Dual-Gauge 260Km/h (AC/DC)
## Maglev
- [x] SC-Maglev
## Guideway
- [x] Guideway Track
## Industrial Tracks
- [x] Narrow CHIPS Concrete Track
- [x] Narrow CHIPS Cobblestone Track
- [x] Narrow CHIPS Dirt Track
- [x] Narrow ISR Track
- [x] Standard CHIPS Concrete Track
- [x] Standard CHIPS Cobblestone Track
- [x] Standard CHIPS Dirt Track
- [x] Standard ISR Track
## Universal Tracks
- [x] Universal Underground (Grass)
- [x] Universal Underground (Concrete)
## Deco Tracks
- [x] Invisible track
- [x] Ballast Ground
- [x] Urban Ground
- [x] High-Speed Ballast Ground
- [x] CHIPS Concrete Ground
- [x] CHIPS Cobblestone Ground
- [x] CHIPS Dirt Ground
- [x] ISR Ground
- [x] Light Concrete Ground

**Comment by Yozora3** [comment]
Overall roadmap:
Finish Modern Shinkansen and Maglev tracks => make 3 more depots for old/modern/urban tracks =>make nesh fence => make params work => release 1.0

**Comment by Yozora3** [comment]
Roadmap for 1st BaNaNas release:
- [ ] Dual-Gauge tracks
- [ ] Guideways
- [ ] Maglevs
- [ ] Make pre-compiled versions of tracks
- [ ] Adjust costs
- [ ] Add speed param
- [ ] At least 1 unique depot for every track sub category
